version: 2

before:
  hooks:
    - go mod tidy
    - make all VERSION={{ .Version }}

builds:
  - id: sensible
    skip: true  # skip goreleaser build since we will be using Makefile

archives:
  - id: sensible
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - build/**

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: |-
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

