version: 2

before:
  hooks:
    - go mod tidy
    - make all VERSION={{ .Version }}

builds:
  - id: sensible
    skip: true  # skip goreleaser build since we will be using Makefile

archives:
  - id: sensible
    builds:
      - sensible
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - build/{{ .Os }}-{{ .Arch }}/sensible{{ if eq .Os "windows" }}.exe{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: |-
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

