name: Code Quality

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-linter:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.0

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8 
        with:
          version: v2.1
